In [ ]:

numpy 
type(arr)
arr.ndim
arr.shape
arr.size
arr.dtype

arr1 = np.arr[[1,2,3],[4,5,6]]
arr2 = np.arr[[5,6,7],[8,9,0]]


operations
arr1+3
arr1+arr2
subtraction 
multiplication 
division
exponent


statistical methods
np.mean axis
np.median axis
np.std
np.min
np.max 
np.var
np.std
np.percentile (arr,25)




In [1]:
import numpy as np

# 📌 Basic Array Attributes
Let's create a NumPy array and explore its properties.

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # A 2D NumPy array
print(type(arr))  # Output: <class 'numpy.ndarray'>
print(arr.ndim)  # Output: 2
print(arr.shape)  # Output: (2, 3)
print(arr.size)  # Output: 6
print(arr.dtype)  # Output: int64 (or int32 based on system)


<class 'numpy.ndarray'>
2
(2, 3)
6
int64


# 📌 Array Operations
Let's create two NumPy arrays:

In [4]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[5, 6, 7], [8, 9, 0]])


# Addition of scalar 
print(arr1 + 3)

# element-wise addition of two arrays 
print(arr1 + arr2)

# subtraction,multiplication, division
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2) 




[[4 5 6]
 [7 8 9]]
[[ 6  8 10]
 [12 14  6]]
[[-4 -4 -4]
 [-4 -4  6]]
[[ 5 12 21]
 [32 45  0]]
[[0.2        0.33333333 0.42857143]
 [0.5        0.55555556        inf]]


/tmp/ipykernel_3985/843380828.py:14: RuntimeWarning: divide by zero encountered in divide
  print(arr1 / arr2)


# 📌 Statistical Methods
NumPy provides powerful statistical functions:

In [5]:
print(np.mean(arr, axis=0))  # Mean of each column
print(np.median(arr, axis=1))  # Median of each row
print(np.std(arr))
print(np.min(arr))  # Smallest value
print(np.max(arr))  # Largest value
print(np.var(arr)) # variance 
print(np.std(arr)) # standard deviation 
print(np.percentile(arr, 25)) # 25th percentile

[2.5 3.5 4.5]
[2. 5.]
1.707825127659933
1
6
2.9166666666666665
1.707825127659933
2.25


Array Properties

<table border="1">
  <tr>
    <th>Feature</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>arr.ndim</code></td>
    <td>Number of dimensions</td>
  </tr>
  <tr>
    <td><code>arr.shape</code></td>
    <td>Shape of the array (rows, columns)</td>
  </tr>
  <tr>
    <td><code>arr.size</code></td>
    <td>Total number of elements</td>
  </tr>
  <tr>
    <td><code>arr.dtype</code></td>
    <td>Data type of elements</td>
  </tr>
</table>

Basic Operations

<table border="1">
  <tr>
    <th>Operation</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>arr + 3</code></td>
    <td>Adds 3 to each element</td>
  </tr>
  <tr>
    <td><code>arr1 + arr2</code></td>
    <td>Element-wise addition</td>
  </tr>
  <tr>
    <td><code>arr1 - arr2</code></td>
    <td>Element-wise subtraction</td>
  </tr>
  <tr>
    <td><code>arr1 * arr2</code></td>
    <td>Element-wise multiplication</td>
  </tr>
  <tr>
    <td><code>arr1 / arr2</code></td>
    <td>Element-wise division</td>
  </tr>
  <tr>
    <td><code>arr1 ** 2</code></td>
    <td>Element-wise exponentiation</td>
  </tr>
</table>

Statistical Functions

<table border="1">
  <tr>
    <th>Function</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>np.mean(arr, axis=0)</code></td>
    <td>Mean of each column</td>
  </tr>
  <tr>
    <td><code>np.median(arr, axis=1)</code></td>
    <td>Median of each row</td>
  </tr>
  <tr>
    <td><code>np.std(arr)</code></td>
    <td>Standard deviation</td>
  </tr>
  <tr>
    <td><code>np.min(arr), np.max(arr)</code></td>
    <td>Minimum and maximum values</td>
  </tr>
  <tr>
    <td><code>np.var(arr)</code></td>
    <td>Variance</td>
  </tr>
  <tr>
    <td><code>np.percentile(arr, 25)</code></td>
    <td>25th percentile</td>
  </tr>
</table>

